### ISSUE TITLE
Issue on 2.2.0

### ISSUE THREAD

**Issue by m0ngr31** [Connormiha/jest-css-modules-transform#12]
```● Test suite failed to run

    Use process(css).then(cb) to work with async plugins
      
      at LazyResult.sync (node_modules/postcss/lib/lazy-result.js:263:23)
      at LazyResult.stringify (node_modules/postcss/lib/lazy-result.js:285:14)
      at LazyResult.get (node_modules/postcss/lib/lazy-result.js:334:25)
      at Object.process (node_modules/jest-css-modules-transform/src/index.js:241:78)
```

**Comment by Connormiha** [comment]
Unfortunately i can't fix it because Jest's transformer works synchronously.
In other words function `process` have to return string result (not promise). This is a limitation of the Jest's API. May be later i will send PR for Jest.

As a temporary solution you can rewrite postcss config for unit tests.
`jest-css-modules-transform-config.js` in root of your project:
```js
module.exports = {
     postcssConfig: {
           plugins: [/* Only sync plugins */]
     }
}
```

**Comment by m0ngr31** [comment]
Thanks that did the trick :+1:

**Comment by davilima6** [comment]
I still needed this workaround for 2.5.0. Should this be re-opened?

**Comment by Connormiha** [comment]
@davilima6 Do you need async plugins?
Unfortunately Jest transform can't work with async code. Jest patches native require. But this `require` works sync(Because commonJS).

**Comment by davilima6** [comment]
Hi, @Connormiha, thanks for the fast reply. TBH I'm not aware about sync/async nature of Jest plugins.

I saw in TS repo [`transpile`](https://github.com/microsoft/TypeScript/blob/afe6f4c95c3a163ae0557b87ca4eb6c0b86a7505/src/testRunner/unittests/services/transpile.ts#L12) returns string but [checking](https://github.com/Connormiha/jest-css-modules-transform/blob/9b9e3d09e6b2e8c4b77dbc6b5f229085a50d2def/__tests__/preprocessor-typescript.js#L5) [jest-css-modules-transform](https://github.com/Connormiha/jest-css-modules-transform/blob/d44b922edbf38ed30f999c40b2292da37d269420/src/index.js#L163) I couldn't follow your comment above that its `process` returns a Promise.

Still I wonder if [newer](https://github.com/microsoft/TypeScript/wiki/Using-the-Compiler-API#transpiling-a-single-file) `transpileModule` API, which deprecates `transpile` and provides an `outputText` attribute, helps here.

**Comment by Connormiha** [comment]
Typescript's transpile return string sync.
`process` expects `string` or object with `code` + `map`.
https://github.com/facebook/jest/blob/master/packages/jest-transform/src/types.ts#L71

This code can't work with `Promise`, becuase inside Jest uses mankey patching for commonjs modules. Jest uses `pirates.js` for patching commonjs https://github.com/ariporad/pirates

**Comment by Connormiha** [comment]
@davilima6 can you list your postcss plugins. May be it possible to fix it with other ways.

**Comment by Connormiha** [comment]
@davilima6 try version `3.1.0`. This problem should be fixed.

**Comment by davilima6** [comment]
Sorry for the delay answering, @Connormiha, before sharing my plugins I wanted to make sure to return to the state of my repo on which the problem happened and didn't quite find the time to repro it. I will try this version and let you know, thanks!!!

Here are my plugins, btw: postcssCustomMedia, postcssImport, postcssCustomProperties, postcssNesting, postcssMixins, postcssColorModFunction, postcssPresetEnv, postcssUrl.

**Comment by davilima6** [comment]
Thanks, @Connormiha, I confirm it now works.
