### ISSUE TITLE
Add support for camel case

### ISSUE THREAD

**Issue by soundstep** [Connormiha/jest-css-modules-transform#13]
When using a webpack css-loader, we can specifiy a `camelCase` option.

```
{
    loader: "css-loader",
    options: {
        modules: true,
        camelCase: true
    }
}
```

Which create a style object like:

```
{
    'button--icon-play': 'button--icon-play',
    buttonIconPlay: 'button--icon-play'
}
```

I tried using the jest-css-modules-transform but the camelCase style were missing.

I instead used a custom jest transform mock:

```const sass = require('node-sass');
const postcss = require('postcss');
const postcssJs = require('postcss-js');
const camelCase = require('camelcase');

module.exports = {
    process(src, filename, config, options) {
        try {
            const cssRendered = sass.renderSync({
                data: src,
                includePaths: [
                    'components/common/styles'
                ]
            });

            const cssString = cssRendered.css.toString();
            const cssObj = postcssJs.objectify(postcss.parse(cssString));
            const mockStyles = {};
            for (var i in cssObj) {
                const classname = i.replace(/^[\.]/, '');
                mockStyles[classname] = classname;
                mockStyles[camelCase(classname)] = classname;
            }
            return 'module.exports = ' + JSON.stringify(mockStyles) + ';';

        } catch(err) {
            console.log('Error in sass-mock', err);
            throw err;
        }
    }
};
```

Is there an easier way to do this? (using the webpack css-loader for example)
Or should jest-css-modules-transform supports camelCase?

**Comment by Connormiha** [comment]
Good point. It will be fixed in next release

**Comment by Connormiha** [comment]
In version `2.3.0` added option `cssLoaderConfig.exportLocalsStyle` equivalent from [css-loader](https://github.com/webpack-contrib/css-loader#exportlocalsstyle).
So you can create file in root of your project `jest-css-modules-transform-config.js`
```js
module.exports = {
   cssLoaderConfig: {
        exportLocalsStyle: 'camelCase'
   }
};
```
@soundstep

**Comment by soundstep** [comment]
Hi,
Thanks for the quick release, this works.
Hijacking my own issue, but is there a way we can specify the path for the `jest-css-modules-transform-config.js`?
We've got a pretty large repo and trying to limit what lives on the root.

**Comment by Connormiha** [comment]
```bash
JEST_CSS_MODULES_TRANSFORM_CONFIG=custom-config-path.js npm test
```
Since `2.4.0`
@soundstep
