### ISSUE TITLE
Add support for css modules :export block

### ISSUE THREAD

**Issue by xumix** [Connormiha/jest-css-modules-transform#14]
Please, add support for exports, it would be extremely usefull with sass/less other preprocessors

Example `.less`
```
@type: "global";
:export {
  red: #db2b21;
  type: @type;
}
.some-style {
display: block;
}
```

the resulting object would look like this: 
```
{ "some-style": "some-style", "red": "#db2b21", "type": "global" }
```

**Comment by Connormiha** [comment]
@xumix good point! Thanks.
It supports since `2.5.0`.

**Comment by xumix** [comment]
wow! thnks for fast response!

**Comment by xumix** [comment]
@Connormiha but I was unable to make my less work, I got all unresolved vars like this:
```
{ type: '@type' }
```

my config looks like this:
```
module.exports = {
    lessConfig: {
        modules: true,
        namedExport: true,
        camelCase: true
    },
    cssLoaderConfig: {
        exportLocalsStyle: "camelCase"
    }
};
```
and jest config:
```
"jest": {
    "moduleFileExtensions": [
      "tsx",
      "ts",
      "less",
      "js",
      "json",
      "jsx"
    ],
    "transform": {
      ".+\\.(css|styl|less|sass|scss)$": "jest-css-modules-transform"
    }
  },
```

**Comment by xumix** [comment]
I've found the problem: `less.render()` is actually async so the file contents get returned before render process is completed

**Comment by xumix** [comment]
The solution looks like this, I suppose
```
    process(src, path, config) {
        let finishFlag = false;
...
        case "less":
            less = less || require("less");
            lessConfig = Object.assign(preProcessorsConfig.lessConfig || {}, { filename: path });
            less.render(src, lessConfig)
                .then(
                    function(output) {
                        textCSS = output.css;
                    },
                    function(error) {
                        if (error) {
                            throw error;
                        }
                    }
                )
                .finally(() => {
                    finishFlag = true;
                });
            break;

        ...

        const deasync = require("deasync");
        while (!finishFlag) {
            deasync.runLoopOnce();
        }

        return moduleTemplate.replace("%s", JSON.stringify(parser.getCSSSelectors(textCSS, path)));
```

**Comment by Connormiha** [comment]
Jest tranform works only synchronously. Unfortunately, this hack is the only solution.

**Comment by Connormiha** [comment]
`deasync` works unstable. Some times it throws error `Assertion failed: (handle->type == UV_TCP || handle->type == UV_TTY || handle->type == UV_NAMED_PIPE), function uv___stream_fd, file ../deps/uv/src/unix/stream.c, line 1617.`. So this is unsafe solution.

**Comment by xumix** [comment]
@Connormiha looks like some bug in nodejs & osx: https://github.com/nodejs/node/issues/8258
also: https://github.com/abbr/deasync/issues/55#issuecomment-346130203

**Comment by xumix** [comment]
@Connormiha any chance you create a repro for the bug? I don't have any osx device available

**Comment by Connormiha** [comment]
This is a very dangerous change. This lib(deasync) is a hack for node.js flow.
Let's try a different path. Show here your `postcss` config. I'll try to come up with something.

**Comment by xumix** [comment]
@Connormiha it is rather simple:
```
module.exports = {
    lessConfig: {
        modules: true,
        namedExport: true,
        camelCase: true
    },
    cssLoaderConfig: {
        exportLocalsStyle: "camelCase"
    }
};
```

**Comment by Connormiha** [comment]
@xumix Try version `3.1.0`
