### ISSUE TITLE
Value of CSS module is 'default'

### ISSUE THREAD

**Issue by Jad2wizard** [Connormiha/jest-css-modules-transform#18]
The content of Hello.less is:
```
.hello{
  text-align: center;
  margin: 20px;
  font-size: 48px;
  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
}

.greeting{
  margin-left: 25px;
  margin-right: 25px;
  font-size: 40px;
  min-width: 50px;
}
```

This is my jest.config.js:
```
module.exports = {
	setupFiles: ['./jest.setup.js'],
	transform: {
		'^.+\\.(css|less)?$':
			'<rootDir>/node_modules/jest-css-modules-transform',
		'^.+\\.js?$': 'babel-jest',
		'^.+\\.ts[x]?$': 'ts-jest'
	},
	moduleFileExtensions: ['tsx', 'ts', 'less', 'js', 'json', 'jsx'],
	moduleNameMapper: {
		'^utils(.*)$': '<rootDir>/src/utils$1',
		'^three-examples(.*)$': '<rootDir>/node_modules/three/examples$1',
		'\\.(css|less)$': 'identity-obj-proxy'
	}
}
```

Hello.test.ts:
```
import * as React from 'react'
import * as enzyme from 'enzyme'
import Hello from './Hello'
import styles from './Hello.less'
// const styles = require('./Hello.less')

it('Test render', () => {
	const hello = enzyme.shallow(<Hello name="jad" />)
	console.log('running...')
	console.log(styles) //output: default
	expect(hello.find('.' + styles.greeting).text()).toEqual('Hello jad')
})
```

After exec `npm test`, I got this error:
```
 Method “text” is meant to be run on 1 node. 0 found instead.

       9 |      console.log('running....')
      10 |      console.log(styles)
    > 11 |      expect(hello.find('.' + styles.greeting).text()).toEqual('Hello jad')
         |                                               ^
      12 | })
```

It seems that the value of styles.greeting is undefined, so the component hello cannot find the className '.undefined'

How can I get the correct value of styles.greeting with pattern of 'modules&localIdentName=[path][name]--[local]--[hash:base64:5]' which is set in the webpack.config.js

Thx

**Comment by Connormiha** [comment]
It looks like you don't have `allowSyntheticDefaultImports` option in `tsconfig` or wrong babel config(commonjs modules for example) for jest env.
`localIdentName` doesn't support. It shouldn effect tests behavior anyway.

**Comment by Jad2wizard** [comment]
Hi Cannormiha, Thank you for your reply. 
I didn't set jest env in my .babelrc. The problem is fixed after I remove the `\\.(css|less)$': 'identity-obj-proxy'` from `moduleNameWrapper`. Here is the content of Hello.test.ts:
```ts
import * as React from 'react'
import * as enzyme from 'enzyme'
import Hello from './Hello'
import styles from './Hello.less'

it('Test render', () => {
	const hello = enzyme.shallow(<Hello name="jad" enthusiasmLevel={2} />)
	console.log('running...')
	console.log(styles)
	expect(hello.find('.' + styles.greeting).text()).toEqual('Hello jad!')
})
```
And the result of jest test is :
<img width="381" alt="屏幕快照 2019-11-27 10 57 23" src="https://user-images.githubusercontent.com/10042204/69689829-f5d2dd80-1104-11ea-9f58-e4422ef3d87b.png">
It seems that the className of `const hello = enzyme.shallow(<Hello name="jad" enthusiasmLevel={2} />)` also not support `localIdentName`.
