### ISSUE TITLE
customize sass compiler

### ISSUE THREAD

**Issue by mushroom-cn** [Connormiha/jest-css-modules-transform#19]
jest-css-modules-transform is using [node-sass](https://www.npmjs.com/package/node-sass), but i want use [sass](https://www.npmjs.com/package/sass).  
I  can not find any options about customizing sass compiler.
How can i change it?

**Comment by Connormiha** [comment]
@mushroom-cn There is no some option for use `sass`. If sass has some API, you can try to use sym links for node_modules/node-sass -> node_modules/sass

**Comment by mushroom-cn** [comment]
@Connormiha got it, thanks.
