### ISSUE TITLE
Any way to include sass dependencies files?

### ISSUE THREAD

**Issue by ramirezcgn** [Connormiha/jest-css-modules-transform#20]
Hi, I'm using "sass-resources-loader" to include global variables in my sass files, but this is not working with jest, is there any way to do this?

Regards

**Comment by Connormiha** [comment]
@ramirezcgn there is no way to connect Webpack's loader to this transformer at the moment.
I will think about it later and will try to find out solution.

**Comment by ramirezcgn** [comment]
Ok, I finally make it works, here are the changes I made just in case it helps anyone:

create a .sassrc.js:
`const path = require('path');
const { EOL } = require('os');

const dependencies = [
  'source/common/global.scss'
];

module.exports = (function() {
  let data = '';
  dependencies.forEach(file => {
    data += '@import "' + file + '";' + EOL;
  });
  return {
    data: data
  };
})();`

and if you are using webpack sass-loader import ("~"), add:

jest-css-modules-transform-config.js:
`const path = require('path');

function testImporter(url) {
  let newUrl = url;
  if (/^~/.test(url)) {
    const testNodeModules = path.resolve(__dirname, 'node_modules') + path.sep;
    newUrl = url.replace(/^~/, testNodeModules);
  }
  return {
    file: newUrl,
  };
}

module.exports = {
  sassConfig: {
    importer: testImporter
  },
  postcssConfig: {
    // eslint-disable-next-line global-require
    plugins: require('autoprefixer')
  },
};`

Thanks @Connormiha anyway

**Comment by Connormiha** [comment]
@ramirezcgn try to use `prepend` section in config in `v4.0.0.`
```js
// file jest-css-modules-transform-config.js
module.exports = {
   prepend: [
       'some/url/vars.scss',
       'some/url/theme.scss',
   ],
};
```
or
```js
// file jest-css-modules-transform-config.js
module.exports = {
   prepend: (filepath) => {
       if (filepath.includes('components')) {
           return [
               'components/vars.scss',
               'components2/vars.scss',
           ];
       }

       return [
            'common/vars.scss',
            'common/vars2.scss',
       ];
   },
};
```

**Comment by ramirezcgn** [comment]
Great!, Thanks!
