### ISSUE TITLE
Support for postcss 8

### ISSUE THREAD

**Issue by tterence** [Connormiha/jest-css-modules-transform#26]
Hello,
thank you for this module. Do you plan on supporting v8 version of postcss ? It depends on postcss7 right now I think.

Upgrading to **postcss 8 AND autoprefixer 10** is breaking the use of autoprefixer, and crashes my tests:

Error: PostCSS plugin autoprefixer requires PostCSS 8

Command failed: node C:\xxx\node_modules\jest-css-modules-transform\dist\postcss.js C:\xxx\src\client\Components\Inputs\input.css C:\xxx\jest-css-modules-transform-config.js C:\xxx\SWAG\postcss.config.js 0

Hope it helps.

**Comment by Connormiha** [comment]
Hello @tterence 
I will add support postcss 8 soon.

**Comment by Connormiha** [comment]
@tterence Try remove `node_modules` and update to version `4.0.2`.
If the problem persists. please attache your `package.json` deps and postcss config.

**Comment by tterence** [comment]
@Connormiha Upgrading to version 4.0.2 solved my issue. Thank you for the quick fix!
