### ISSUE TITLE
Support of sass instead node-sass

### ISSUE THREAD

**Issue by krutoo** [Connormiha/jest-css-modules-transform#28]
Hello. Can `jest-css-modules-transform` work with `sass` module instead `node-sass`

`node-sass` is depreacated now and it is now supports new features of Sass/SCSS.

**Comment by Connormiha** [comment]
@krutoo Try to use last version `4.1.0`. Now it takes `node-sass` only if `sass` not found in node_modules.

**Comment by krutoo** [comment]
@Connormiha thank you, it works
