### ISSUE TITLE
Support injecting generated CSS into the document

### ISSUE THREAD

**Issue by ashubham** [Connormiha/jest-css-modules-transform#30]
This repo https://github.com/dferber90/jest-transform-css can be used to inject styles into the document head for visual regression testing. But the library is limited in what it supports (does not support scss for example).

I think this lib takes care of most of the stuff, except injecting the styles in the document.

Might be good to add an option for that.

**Comment by Connormiha** [comment]
Good point.

**Comment by ashubham** [comment]
@Connormiha Created a PR, PTAL

**Comment by Connormiha** [comment]
Implemented in `v4.2.0`.
