### ISSUE TITLE
First run of tests with TS fails

### ISSUE THREAD

**Issue by krutoo** [Connormiha/jest-css-modules-transform#33]
Hi, i use `jest-css-modules-transform` with typescript and `typescript-plugin-css-modules` and when 

Here is example repo:
https://github.com/krutoo/jest-ts-css-modules

I run it on **node js 14.15.5**

When run:
```bash
npm run test -- --watchAll
```

First run fails with:
```
  ● Test suite failed to run

    src/components/second/index.tsx:2:20 - error TS2307: Cannot find module './second.scss' or its corresponding type declarations.

    2 import styles from './second.scss';
                         ~~~~~~~~~~~~~~~
```

**important:** restart by Enter key on keyboard removes error

Can you help me to understand: is this a bug in the `jest-css-modules-transform` package? Or it is `typescript-plugin-css-modules` issue?

**Comment by krutoo** [comment]
Looks like adding `custom.d.ts` accroding to this article solves problem:
https://github.com/mrmckeb/typescript-plugin-css-modules#custom-definitions

**Comment by Connormiha** [comment]
Yes. This is problem of TypeScript, not in transfromer. You have to describe `types` for css files.
