### ISSUE TITLE
:export blocks should get camelCase versions of their outputs

### ISSUE THREAD

**Issue by dgoldstein0** [Connormiha/jest-css-modules-transform#49]
a css module file in my codebase has an `:export` block, e.g. 

```
// foo.css
:export {
    page-margin: 16px;
}

// foo.js
import {pageMargin} from "./foo.css";
```

However, this transform only seems to give us `"page-margin"` to use, i.e. we'd have to change foo.js to `import styles from "./foo.css"; const pageMargin = styles["page-margin"];`.  I expected the camel casing to be implemented for us, as it seems to be implemented by postcss-modules and so our build system already supports the syntax (entirely by accident).

**Comment by dgoldstein0** [comment]
I had to fix this locally so ended up tracking this down to https://github.com/Connormiha/jest-css-modules-transform/blob/master/src/parser.ts#L73.  Probably `exportsLocalStyle` should be taken into account here.

**Comment by Connormiha** [comment]
@dgoldstein0 Thanks for report and sorry for delay. Try to last release.

**Comment by dgoldstein0** [comment]
thanks! just upgraded to 4.4.2 and it solves this problem
