### ISSUE TITLE
How to use this with localIndentName?

### ISSUE THREAD

**Issue by MrKou47** [Connormiha/jest-css-modules-transform#6]
How could i set localIndentName options for this processor?

**Comment by Connormiha** [comment]
Thnaks for your request. At the moment there is no such features. For the most test cases it is not so important. Maybe in future versions will be added.

**Comment by MrKou47** [comment]
Thanks.But i think it might be important for the snapshot test, i want to test it should be equal to the bundled file,If i want to test snapshot:
```js
<div className=“index__container__3SFSH” />
```

but actually i got this:
```js
<div className=“index__container” />
```

it seems a bad test...Hope you add this feature 👍

**Comment by tf** [comment]
Had the same problem. Went with [`jest-css-modules-processor`](https://github.com/MrKou47/jest-css-modules-processor).
