### ISSUE TITLE
css classes are not injected when using scss with css modules

### ISSUE THREAD

**Issue by alveshelio** [Connormiha/jest-css-modules-transform#9]
Hi,

I have a project with the following stack: React/Redux/Typescript/SCSS/CSSModules

We are using jest with react-testing-library to test our components that are developed in storybook and then published to a private repository.

This is my jest.config.js file
```
module.exports = {
  "roots": [
    "<rootDir>/src"
  ],
  "transform": {
    "^.+\\.tsx?$": "ts-jest"
  },
  "testRegex": "(/__tests__/.*|(\\.|/)(test|spec))\\.tsx?$",
  "moduleFileExtensions": [
    "ts",
    "tsx",
    "js",
    "jsx",
    "json",
    "node"
  ],
  testPathIgnorePatterns: ["/node_modules/"],
  "moduleNameMapper": {
    ".+\\.(css|styl|less|sass|scss|svg)$": "<rootDir>/node_modules/jest-css-modules-transform",
  },
  "transformIgnorePatterns" : [
    "^.d.ts?$"
  ],
}
```

Component I'm testing ChipStatus.tsx
```
import * as React from "react"

import * as s from "./ChipStatus.scss"
import { IChipStatusProps } from "."

const ChipStatus: React.FunctionComponent<IChipStatusProps> = props => {
  return <div className={s.active}>{props.placeholder}</div>
}

export default ChipStatus
```

And this is my test ChipStatus.test.tsx
```
import * as React from "react"
import { render } from "react-testing-library"
import "jest-dom/extend-expect"

import ChipStatus from "./ChipStatus"
import { EChipStatus } from "./index"

test("ChipStatus inactive", async () => {
  const { container, debug } = render(
    <ChipStatus status={EChipStatus.ACTIVE} placeholder={"texte active"} />
  )
  expect(container.firstChild).toHaveClass("active");
  expect(container.firstChild).toHaveTextContent("texte active")
})
```

This test should pass, however it fails because there's no class injected in my component

This is the debug() of my component
```
<div
                      class=""
                    >
                      <p
                        class="MuiTypography-root-136 MuiTypography-body1-145"
                      >
                        Active
                      </p>
                    </div>
```

As you can see, I'm missing the class active. What troubles me is that in a component from Material-ui we have the class that is injected, but I guess that when the test runs, the scss file is not being compiled into css and the class is not injected.

Am I missing something in my set up?

**Comment by Connormiha** [comment]
@alveshelio  Where does this record come from and why is svg here?
```js
"moduleNameMapper": {
    ".+\\.(css|styl|less|sass|scss|svg)$": "<rootDir>/node_modules/jest-css-modules-transform",
  },
```

According to the documentation should be
```js
"transform": {
  ".+\\.scss$": "jest-css-modules-transform"
},
```

**Comment by Connormiha** [comment]
By the way. You can use default import for styles.
```js
import s from "./ChipStatus.scss"
```

**Comment by alveshelio** [comment]
Hi @Connormiha 

Thank you very much for your quick reply. 

Here's my new jest.config.js file
```
module.exports = {
  "roots": [
    "<rootDir>/src"
  ],
  "transform": {
    "^.+\\.tsx?$": "ts-jest",
    ".+\\.scss$": "jest-css-modules-transform",
    "^.+\\.svg$": "jest-svg-transformer",
  },
  "testRegex": "(/__tests__/.*|(\\.|/)(test|spec))\\.tsx?$",
  "moduleFileExtensions": [
    "ts",
    "tsx",
    "js",
    "jsx",
    "json",
    "node"
  ],
  testPathIgnorePatterns: ["/node_modules/"],
  "moduleNameMapper": {
    ".+\\.css$": require.resolve("./test/style-mock"),
  },
  "transformIgnorePatterns" : [
    "^.d.ts?$"
  ],
}
```

I've created a new file /test/style-mock.js with this content
`module.exports={}`

However, I'm still having the same problems, 

Here's the output of my test
```
<body>
        <div>
          <div
            class=""
          >
            texte active
          </div>
        </div>
      </body>

  ● ChipStatus Active

    expect(element).toHaveClass("active")

    Expected the element to have class:
      active
    Received:

      11 |   )
      12 |   debug()
    > 13 |   expect(container.firstChild).toHaveClass("active")
         |                                ^
      14 |   expect(container.firstChild).toHaveTextContent("texte active")
      15 | })
      16 |

      at Object.<anonymous> (src/components/chipstatus/ChipStatus.test.tsx:13:32)
      at src/components/chipstatus/ChipStatus.test.tsx:7:71
      at Object.<anonymous>.__awaiter (src/components/chipstatus/ChipStatus.test.tsx:3:12)
      at Object.<anonymous>.test (src/components/chipstatus/ChipStatus.test.tsx:8:38)
```

**Comment by Connormiha** [comment]
Show me your `ChipStatus.scss` file.

**Comment by alveshelio** [comment]
Actually, I don't have a ChipStatus.scss file, let me try to explain a but ty setup. I'm developing my components in storybook, in there I use css modules but instead of using scss, I'm using css.
However, in my project, I'm using scss files with css modules.

Because I was not able to test my components in storybook (unable to check if the element has a class) I've decided to test the component directly in my project, so I've copied the component from storybook into my project.

I've modified my jest.config.js to add 
".+\\.css$": "jest-css-modules-transform", to transform

This is my ChipStatus.css file
```
.active p,
.error p,
.deleted p,
.inactive p,
.incomplete p {
    position: relative;
    padding-left: 24px;
    display: inline;
}

.active p::before,
.error p::before,
.deleted p::before,
.inactive p::before,
.incomplete p::before {
    content: "";
    width: 16px;
    height: 16px;
    border-radius: 50%;
    background-color: #05af00;
    display: block;
    position: absolute;
    left: 0;
    top: 50%;
    margin-top: -8px;
}

.error p::before {
    background-color: #f00;
}

.incomplete p::before {
    background-color: #fb7100;
}

.deleted p::before {
    background-color: #000000;
}

.inactive p::before {
    background-color: #676767;
}
```

Here are the files I have in this component
scr/components/chipstatus
  -> ChipStatus.css
  -> ChipStatus.css.d.ts
  -> ChipStatus.test.tsx
  -> ChipStatus.tsx
  -> index.ts

But my tests are still not passing.
I've just noticed something really strange, I was doing a test on a button and I was passing disabled to it and then I was checking if the button had attribute disabled, however the test was failing too and when I output the html of the button I get this.
```
<div><button class="MuiButtonBase-root-27 MuiButtonBase-disabled-28 MuiButton-root-1 MuiButton-text-3 MuiButton-flat-6 MuiButton-disabled-21" data-qa="button" disabled="" tabindex="-1" type="button"><span class="MuiButton-label-2">label</span></button></div>
```
So I'm not sure anymore if it has anything to do with your plugin or if it has something to do with jest or how I've configured it :(

**Comment by Connormiha** [comment]
You impotred `style` form `.scss` in your component. Of course it can't work correсt if this file is empty.

**Comment by alveshelio** [comment]
I've just created a simple component to test if it would load the styles and it does indeed. 
This is my component 
```
import * as React from "react"

import s from "./SimpleButton.scss"

const SimpleButton = () => <button className={s.SimpleButton}>My simple button</button>

export default SimpleButton

and in Simplebutton.scss I have
```
.SimpleButton {
  border: 2px solid deeppink;
  padding: 5px 10px;
  font-size: 16px;
  text-transform: uppercase;
}
```

And I do get the class injected.

I think I know what the problem is. Actually, when I do `import s from './Simplebutton.scss'` the class name is present, however when I do `import * as s from './Simplebutton.scss'` the css class is not present.

The problem is that we have this file: ChipStatus.css.d.ts with the following content
```
export const container: string
export const active: string
export const error: string
export const incomplete: string
export const deleted: string
export const inactive: string
```
This is how we type our css, and we cannot do `import s from './Simplebutton.scss'`

I'm out of ideas how to fix this :(

**Comment by Connormiha** [comment]
With same scss content you will receive that result:
```css
.SimpleButton {
  border: 2px solid deeppink;
  padding: 5px 10px;
  font-size: 16px;
  text-transform: uppercase;
}
```
=>
```js
{
  SimpleButton: 'SimpleButton'
}
```

If you want to get classes `active`, `container`, etc. You have to create scss file with css classes:
```css
.active {
    //
}

.container {
    //
}
```

Exactly the same behavior will be with Webpack's css modules.

**Comment by alveshelio** [comment]
I'm not sure I understand your comment above.

What do you mean by 
With same scss content you will receive that result:

.SimpleButton {
  border: 2px solid deeppink;
  padding: 5px 10px;
  font-size: 16px;
  text-transform: uppercase;
}
=>

{
  SimpleButton: 'SimpleButton'
}

Regarding the classes, this is what I have in my file ChipStatus.scss, I have .active {} .deleted {}, etc... however the problem is with typescript, when I try to import the css styles with `import s from './ChipStatus.scss'` typescript complains.

**Comment by Connormiha** [comment]
Typescript has nothing to do with this at all.
`jest-css-modules-transform` just simulates webpack behavior. It looks like css-loader with `localIdentName: [local]`. See Reamdme file.

**Comment by alveshelio** [comment]
OK, I understand better what this module does, however, I don't understand why when I do `import * as s from 'ChipStatus.scss'` the CSS class in not injected, where if I do `import s from 'ChipStatus.scss' the class is injected.

**Comment by m0ngr31** [comment]
> OK, I understand better what this module does, however, I don't understand why when I do import * as s from 'ChipStatus.scss' the CSS class in not injected, where if I do import s from 'ChipStatus.scss' the class is injected.

This appears to be fixed now.
